package simulator

import (
	"fmt"
	"io"
	"math/rand"

	"github.com/shopspring/decimal"
)

// Event is one PV-credit event in a period (a package purchase / ROI tick).
type Event struct {
	ID     int64
	NodeID int64
	PV     decimal.Decimal // PV credited (typically = package price)
	USD    decimal.Decimal // USD inflow this event produced for the company
}

// PeriodResult records what happened in one binary period.
type PeriodResult struct {
	Period            int
	NewAffiliates     int
	Inflows           decimal.Decimal
	Events            int
	Candidates        int
	ProjectedOutflows decimal.Decimal
	Theta             decimal.Decimal
	// BinaryPaid is the net paid by the binary tree block stream only.
	// TotalPaid includes BinaryPaid plus yield, points, ranks, referral,
	// royalty and released paused carry.
	BinaryPaid decimal.Decimal
	// ReleasedCarryPaid is paused R1 carry released after the affiliate
	// re-qualified in this period. It is real money out, separated so the
	// disbursement report can reconcile every dollar in TotalPaid.
	ReleasedCarryPaid decimal.Decimal
	TotalPaid         decimal.Decimal
	Margin            decimal.Decimal
	// CompanyFund mirrors Margin with the business-facing name:
	// inflows minus all money distributed in the period.
	CompanyFund decimal.Decimal
	// CumulativeCompanyFund is the running retained fund through this period.
	CumulativeCompanyFund decimal.Decimal
	Breakage              Breakage
	SolvencyOK            bool
	// ADR-0013 R1
	RepurchaseInflows decimal.Decimal // USD generated by R1 compliance this period
	UnqualifiedR1     int             // affiliates failing R1 at end of period

	// Carry holding: Σ Node.PausedCarry at end of period. Shows how much
	// money P-B is sitting on. If this grows unbounded, the plan is
	// effectively never paying it back.
	PausedCarryHeld decimal.Decimal

	// R2 — yield (ADR-0015). USD paid this period as 25%/12 of package to
	// affiliates with ≥1 direct on each side. Counts toward TotalPaid.
	YieldPaid      decimal.Decimal
	YieldQualified int // affiliates qualified for R2 at end of period

	// Liquidity: total deposited capital still locked (PackageDepositPeriod
	// within CapitalLockPeriods). Reported, doesn't affect θ.
	LockedCapital decimal.Decimal

	// R3 — points bonus (ADR-0016). USD paid this period from the points
	// stream. Non-zero only on cadence periods. Counts toward TotalPaid.
	PointsBonusPaid decimal.Decimal
	// PointsHeld = Σ Node.PointsAccrued at end of period. Inventory of
	// pending points-bonus claims. Drops to 0 right after a payout.
	PointsHeld decimal.Decimal

	// Carrera de rangos (ADR-0017/0018). Bonos one-time pagados este período
	// (netos, post-θ) y total acumulado de hitos alcanzados en la red.
	RankBonusPaid decimal.Decimal
	RanksAchieved int

	// Referido gen-1 + regalía gen-2 (ADR-0018), netos post-θ.
	ReferralPaid decimal.Decimal
	RoyaltyPaid  decimal.Decimal
}

// RunScenario executes the full Monte Carlo of `Periods` binary closes.
// It returns the per-period results and a final aggregate.
//
// Algorithm per period:
//  1. Maybe add new affiliates (growth).
//  2. Generate package-purchase events for all affiliates whose package
//     hasn't been closed by T2 yet.
//  3. Enumerate candidates (ancestors paid for those events).
//  4. Apply T2 & T3 caps in-memory.
//  5. Compute θ over the period.
//  6. Mark payments (net = gross × θ), update node state.
//  7. Decay carry (β-periods).
func RunScenario(s Scenario, w io.Writer) ([]PeriodResult, error) {
	if s.Plan.BlockSize <= 0 {
		return nil, fmt.Errorf("scenario: BlockSize must be > 0")
	}
	if s.InitialAffiliates < 1 {
		return nil, fmt.Errorf("scenario: InitialAffiliates must be >= 1")
	}

	tree := NewTree(s.Seed)
	rootID := tree.CreateRoot()
	rng := tree.Seed()

	// Seed initial population using the same sponsor distribution as growth.
	// Only the first affiliate hangs from root; after that, every placement has
	// a real non-root sponsor so Q_L/Q_R tree rules are exercised from period 1.
	for i := 0; i < s.InitialAffiliates; i++ {
		sponsor := rootID
		if tree.Size() > 1 {
			sponsor = pickSponsorByDistribution(rng, tree, rootID, s.SponsorDistribution, s.SponsorPowerLawAlpha)
		}
		price := pickPrice(rng, s.PackagePrices)
		id := PlaceWithStrategy(tree, sponsor, price, s.Strategy, rng)
		markFounder(tree, id, s.Plan, rng)
	}

	cumulativeMargin := decimal.Zero
	results := make([]PeriodResult, 0, s.Periods)
	eventCounter := int64(0)

	// Mitigación B (cuotas de rango): calendario de pagos diferidos.
	// Al cruzar un hito en el período p, el bono se divide en N cuotas
	// programadas en p, p+c, p+2c... (la última lleva el remanente para
	// que el total sea exacto). El hito se marca alcanzado en p.
	rankSchedule := map[int][]payEntry{}
	scheduleRankBonus := func(nodeID int64, bonus decimal.Decimal, period int) {
		n := s.Plan.RankInstallments
		c := s.Plan.RankInstallmentCadence
		if n <= 1 || c <= 0 {
			rankSchedule[period] = append(rankSchedule[period], payEntry{nodeID, bonus})
			return
		}
		per := bonus.Div(decimal.NewFromInt(int64(n))).RoundDown(2)
		paid := decimal.Zero
		for i := 0; i < n; i++ {
			amt := per
			if i == n-1 {
				amt = bonus.Sub(paid) // remanente exacto en la última cuota
			}
			rankSchedule[period+i*c] = append(rankSchedule[period+i*c], payEntry{nodeID, amt})
			paid = paid.Add(per)
		}
	}

	for p := 1; p <= s.Periods; p++ {
		tree.SetPeriod(p)

		// 0. ADR-0013 R1: roll for repurchases on affiliates failing the
		// rule. Adds to inflows; on compliance, resets the affiliate's
		// LastPurchaseAt so they re-qualify and releases any P-B carry.
		repurchaseInflows, releasedCarry := processRepurchases(tree, rootID, s.Plan, s.PackagePrices, rng, p)

		// 1. Growth — add new affiliates.
		newCount := int(float64(tree.Size()-1) * s.GrowthRate)
		for i := 0; i < newCount; i++ {
			sponsor := pickSponsorByDistribution(rng, tree, rootID, s.SponsorDistribution, s.SponsorPowerLawAlpha)
			price := pickPrice(rng, s.PackagePrices)
			id := PlaceWithStrategy(tree, sponsor, price, s.Strategy, rng)
			markFounder(tree, id, s.Plan, rng)
		}

		// 2. Generate events. v1 model: each non-closed affiliate produces
		// one PV-credit event per period equal to package_price (1 USD = 1 PV).
		// Apply inflow shock if scheduled.
		shock := decimal.NewFromInt(1)
		if m, ok := s.InflowShock[p]; ok {
			shock = decimal.NewFromFloat(m)
		}

		events := make([]Event, 0, tree.Size())
		inflows := decimal.Zero
		for _, n := range allNodes(tree, rootID) {
			if n.PackageClosed || n.PackagePrice.IsZero() {
				continue
			}
			// Recurring package contribution (ROI-like). Modeled as a fraction
			// of price per period — here: 5% of price, capped by shock.
			contrib := n.PackagePrice.Mul(decimal.NewFromFloat(0.05)).Mul(shock).Round(2)
			eventCounter++
			events = append(events, Event{
				ID:     eventCounter,
				NodeID: n.ID,
				PV:     contrib,
				USD:    contrib,
			})
			inflows = inflows.Add(contrib)
		}
		// R1 repurchases add to the period's inflow pool (used by θ + treasury).
		inflows = inflows.Add(repurchaseInflows)

		// 3. Enumerate
		candidates := enumerateCandidates(tree, events, s.Plan)

		// 4. Caps
		afterCaps, br := applyCaps(candidates, tree, s.Plan)

		// 4b. R2 yield candidates (25%/year, paid every YieldCadencePeriods).
		// D2: yield is paid IN FULL — it does NOT go through θ, same contract
		// as the production CD-ROI stream (cd_roi.go, H1). Consecuencia clave:
		// el yield tampoco cuenta en `projected` (el denominador de θ) — se
		// excluye igual que el concepto 1006 en producción, que se suma a
		// total_paid después de θ y nunca a projected (binary_close.go). Ver la
		// construcción de projected más abajo. D3: it DOES count against T2
		// (package lifetime cap), pre-capped to the node's remaining cap — see
		// the yield payment loop below.
		yieldCands := computeYieldCandidates(tree, rootID, s.Plan, p)

		// 4c. R3 points bonus candidates (1 punto / block, $1/punto, monthly).
		// Same caps as binary block (T1+T2+T3). Capped HERE so projected
		// reflects post-cap amounts entering θ.
		pointsCandsRaw := computePointsBonusCandidates(tree, rootID, s.Plan, p)
		var pointsAfterCaps []Candidate
		var pointsBr Breakage
		if len(pointsCandsRaw) > 0 {
			pointsAfterCaps, pointsBr = applyCaps(pointsCandsRaw, tree, s.Plan)
			br.DailyCapHits += pointsBr.DailyCapHits
			br.DailyCapReducedUSD = br.DailyCapReducedUSD.Add(pointsBr.DailyCapReducedUSD)
			br.PackageCapHits += pointsBr.PackageCapHits
			br.PackageCapReducedUSD = br.PackageCapReducedUSD.Add(pointsBr.PackageCapReducedUSD)
		}

		// 4d. Carrera de rangos (ADR-0017/0018): ascensos recién calificados.
		// Se computa DESPUÉS de enumerateCandidates (que acreditó el PV de
		// carrera vía AddPV). T1 sólo — entra a θ, bypassa T2/T3.
		// El hito se marca YA (one-time, no re-emisión); el pago se programa
		// vía scheduleRankBonus (cuotas si RankInstallments > 1).
		for _, r := range computeRankCandidates(tree, rootID, s.Plan) {
			if anc := tree.Get(r.NodeID); anc != nil && r.RankIdx > anc.RankAchieved {
				anc.RankAchieved = r.RankIdx
			}
			scheduleRankBonus(r.NodeID, r.Bonus, p)
		}
		// Cuotas que vencen ESTE período (incluye la primera del ascenso de
		// hoy). Entran a θ como cualquier stream.
		rankDue := rankSchedule[p]
		delete(rankSchedule, p)

		// 4e. Referido gen-1 + regalía gen-2 (ADR-0018). T1 sólo.
		refCands, royCands := computeReferralRoyalty(tree, events, s.Plan)

		// 5. θ over projected total post-caps
		//    (blocks + points + rangos + referido + regalía).
		//
		// El yield NO entra en projected (D2): se paga completo, sin θ, así que
		// NO debe inflar el denominador de θ. Esto refleja EXACTAMENTE a
		// producción, donde el CD-ROI (concepto 1006) se suma a total_paid
		// DESPUÉS de θ y nunca a projected (binary_close.go: roiWindow). Si el
		// yield contara aquí, deprimiría θ (θ_sim < θ_prod) y estrangularía los
		// demás streams → el simulador pagaría de MENOS y subestimaría el breach.
		// Los demás streams v2 (puntos, rangos, referido, regalía) SÍ entran a
		// projected — igual que v2.ProjectedTotal() en producción.
		projected := decimal.Zero
		for _, c := range afterCaps {
			projected = projected.Add(c.GrossAmount)
		}
		for _, c := range pointsAfterCaps {
			projected = projected.Add(c.GrossAmount)
		}
		for _, r := range rankDue {
			projected = projected.Add(r.Amount)
		}
		for _, e := range refCands {
			projected = projected.Add(e.Amount)
		}
		for _, e := range royCands {
			projected = projected.Add(e.Amount)
		}
		theta := computeTheta(s.Plan.TreasuryAlpha, inflows, projected)

		// 6. Apply payments (gross × θ). Update node state.
		//
		// CRITICAL: RoundDown (toward zero) is required for T1 to hold under
		// rounding. Banker's/half-up rounding can produce Σ rounded nets >
		// Σ unrounded nets > α·inflows, breaching solvency by pennies. The
		// production binary_close.go uses .Round(2) but the DB post-commit
		// fn_verify_period_solvency has a tolerance; the simulator is stricter.
		totalPaid := decimal.Zero
		pausedRouted := decimal.Zero  // P-B: stashed into carry
		reductionLost := decimal.Zero // P-C: kept by company
		// R3 — points earned from blocks paid THIS period, collected here and
		// applied to Node.PointsAccrued only AFTER the points-bonus
		// reset below (H2 fix, see that section for why).
		pointsToAccrue := map[int64]decimal.Decimal{}
		for _, c := range afterCaps {
			net := c.GrossAmount.Mul(theta).RoundDown(2)
			if net.Sign() <= 0 {
				continue
			}
			anc := tree.Get(c.AncestorID)
			if anc == nil {
				continue
			}

			// ADR-0013 R1: route net based on pause mode if unqualified.
			qualified := isQualifiedR1(anc, s.Plan)
			if !qualified {
				switch s.Plan.PauseMode {
				case "carry":
					// P-B: accumulate into PausedCarry. Don't credit wallet.
					anc.PausedCarry = anc.PausedCarry.Add(net)
					anc.PausedCarryUpdatedAt = p
					pausedRouted = pausedRouted.Add(net)
					continue
				case "reduce":
					// P-C: pay only ReductionFactor × net. Rest stays w/ company.
					reduced := net.Mul(s.Plan.PauseReductionFactor).RoundDown(2)
					reductionLost = reductionLost.Add(net.Sub(reduced))
					net = reduced
					if net.Sign() <= 0 {
						continue
					}
				}
				// "skip" never reaches here (filtered in enumerateCandidates).
			}

			anc.PeriodPaid = anc.PeriodPaid.Add(net)
			anc.PackagePaid = anc.PackagePaid.Add(net)
			if anc.PackagePaid.GreaterThanOrEqual(s.Plan.LifetimeCapFactor.Mul(anc.PackagePrice)) {
				anc.PackageClosed = true
			}
			totalPaid = totalPaid.Add(net)

			// R3 — compute points earned from blocks actually paid (after θ
			// floor). NOT applied to anc.PointsAccrued here — collected into
			// pointsToAccrue and applied AFTER the points-bonus reset below,
			// so this period's own points survive into the next cadence
			// cycle instead of being wiped by the reset (H2 fix).
			if s.Plan.PointsBonusEnabled && c.NewBlocks > 0 {
				effBlocks := decimal.NewFromInt(int64(c.NewBlocks)).Mul(theta).Floor()
				if effBlocks.Sign() > 0 {
					pointsToAccrue[c.AncestorID] = pointsToAccrue[c.AncestorID].Add(
						effBlocks.Mul(s.Plan.PointsPerBlock))
				}
			}
		}
		binaryPaid := totalPaid
		// R2 yield payments (D2: paid in full, no θ; D3: consumes T2, capped
		// to remaining — same contract as cd_roi.go's H1-T2 handling).
		yieldPaid := decimal.Zero
		for _, y := range yieldCands {
			anc := tree.Get(y.NodeID)
			if anc == nil {
				continue
			}
			capTotal := s.Plan.LifetimeCapFactor.Mul(anc.PackagePrice)
			remaining := capTotal.Sub(anc.PackagePaid)
			if remaining.Sign() <= 0 {
				continue // T2 already exhausted
			}
			net := y.Amount
			if net.GreaterThan(remaining) {
				net = remaining // pre-cap to remaining, like cd_roi.go
			}
			if net.Sign() <= 0 {
				continue
			}
			// Yield credits the affiliate and consumes T2 (PackagePaid),
			// same as any other stream that counts against the lifetime
			// cap. Does NOT bump PeriodPaid (T3) — that tracks per-period
			// binary commissions only, unrelated to the lifetime cap.
			anc.PackagePaid = anc.PackagePaid.Add(net)
			if anc.PackagePaid.GreaterThanOrEqual(capTotal) {
				anc.PackageClosed = true
			}
			yieldPaid = yieldPaid.Add(net)
		}

		// R3 points bonus payout (only on cadence periods).
		// Already capped via applyCaps above; just apply θ + accumulate.
		pointsBonusPaid := decimal.Zero
		if len(pointsAfterCaps) > 0 {
			for _, c := range pointsAfterCaps {
				net := c.GrossAmount.Mul(theta).RoundDown(2)
				if net.Sign() <= 0 {
					continue
				}
				anc := tree.Get(c.AncestorID)
				if anc == nil {
					continue
				}
				// Counts against T2 / T3 (we already capped) and accumulates
				// like a regular bonus into PeriodPaid + PackagePaid.
				anc.PeriodPaid = anc.PeriodPaid.Add(net)
				anc.PackagePaid = anc.PackagePaid.Add(net)
				if anc.PackagePaid.GreaterThanOrEqual(s.Plan.LifetimeCapFactor.Mul(anc.PackagePrice)) {
					anc.PackageClosed = true
				}
				pointsBonusPaid = pointsBonusPaid.Add(net)
			}
			// Reset accrued points after payout (whether paid or not — caps
			// destroy excess, same as block bonus over T2/T3).
			resetPointsAccrued(tree, rootID)
		}

		// R3 — apply points earned from blocks paid THIS period, AFTER the
		// reset above (H2 fix). Doing this before the reset was the bug: the
		// cadence period's own points-earning payments got wiped by the same
		// period's reset instead of surviving to be paid on the NEXT cadence
		// boundary. Runs every period (not gated on cadence), same as
		// production's AccruePoints call placement in binary_close.go
		// (after PayV2Streams).
		for ancID, pts := range pointsToAccrue {
			if anc := tree.Get(ancID); anc != nil {
				anc.PointsAccrued = anc.PointsAccrued.Add(pts)
			}
		}

		// Carrera de rangos — cuotas que vencen este período × θ. El hito ya
		// quedó marcado al cruzar (arriba); cada cuota se liquida al neto de
		// SU período, sin reintentos — mismo contrato que
		// affiliate_rank_achieved + calendario de cuotas.
		rankBonusPaid := decimal.Zero
		for _, r := range rankDue {
			net := r.Amount.Mul(theta).RoundDown(2)
			if net.Sign() > 0 {
				rankBonusPaid = rankBonusPaid.Add(net)
			}
		}

		// Referido gen-1 + regalía gen-2 — × θ, sin T2/T3.
		referralPaid := decimal.Zero
		for _, e := range refCands {
			net := e.Amount.Mul(theta).RoundDown(2)
			if net.Sign() > 0 {
				referralPaid = referralPaid.Add(net)
			}
		}
		royaltyPaid := decimal.Zero
		for _, e := range royCands {
			net := e.Amount.Mul(theta).RoundDown(2)
			if net.Sign() > 0 {
				royaltyPaid = royaltyPaid.Add(net)
			}
		}

		// θ-haircut = gross proyectado − neto pagado de los streams SUJETOS a θ
		// − diversiones por pausa. El yield NO entra (ni en projected ni aquí):
		// se paga completo sin θ, así que no participa en la reducción por θ. Sí
		// se descuenta el resto de streams θ-sujetos. (Antes projected incluía
		// el yield y se restaba yieldPaid; ahora ambos salen juntos para que la
		// métrica siga significando "lo que θ retuvo".)
		br.ThetaReducedUSD = projected.Sub(totalPaid).Sub(pointsBonusPaid).
			Sub(rankBonusPaid).Sub(referralPaid).Sub(royaltyPaid).
			Sub(pausedRouted).Sub(reductionLost)
		// Released P-B carry is real money out of the company this period.
		totalPaid = totalPaid.Add(releasedCarry)
		totalPaid = totalPaid.Add(yieldPaid)
		totalPaid = totalPaid.Add(pointsBonusPaid)
		totalPaid = totalPaid.Add(rankBonusPaid)
		totalPaid = totalPaid.Add(referralPaid)
		totalPaid = totalPaid.Add(royaltyPaid)

		// Consume PV: subtract paid blocks worth of points from BOTH legs.
		// Surplus on stronger side becomes carry.
		consumePVAfterPayments(tree, afterCaps, s.Plan, theta)

		// 7. Decay carry: every β periods we wipe expired carry.
		if p%s.Plan.CarryDecayPeriods == 0 {
			expired := decayCarry(tree, rootID)
			br.CarryExpiredUSD = expired
		}

		// Reset period-paid counters for next period (T3 is per-period).
		for _, n := range allNodes(tree, rootID) {
			n.PeriodPaid = decimal.Zero
		}

		margin := inflows.Sub(totalPaid)
		cumulativeMargin = cumulativeMargin.Add(margin)

		maxAllowed := s.Plan.TreasuryAlpha.Mul(inflows)
		solvent := totalPaid.LessThanOrEqual(maxAllowed.Add(decimal.NewFromFloat(0.01)))

		// End-of-period metrics: carry holding, locked capital, R2 qualified.
		pausedCarryHeld := decimal.Zero
		lockedCapital := decimal.Zero
		for _, n := range allNodes(tree, rootID) {
			pausedCarryHeld = pausedCarryHeld.Add(n.PausedCarry)
			if s.Plan.CapitalLockPeriods > 0 &&
				p-n.PackageDepositPeriod < s.Plan.CapitalLockPeriods {
				lockedCapital = lockedCapital.Add(n.PackagePrice)
			}
		}

		res := PeriodResult{
			Period:                p,
			NewAffiliates:         newCount,
			Inflows:               inflows,
			Events:                len(events),
			Candidates:            len(candidates),
			ProjectedOutflows:     projected,
			Theta:                 theta,
			BinaryPaid:            binaryPaid,
			ReleasedCarryPaid:     releasedCarry,
			TotalPaid:             totalPaid,
			Margin:                margin,
			CompanyFund:           margin,
			CumulativeCompanyFund: cumulativeMargin,
			Breakage:              br,
			SolvencyOK:            solvent,
			RepurchaseInflows:     repurchaseInflows,
			UnqualifiedR1:         countUnqualifiedR1(tree, rootID, s.Plan),
			PausedCarryHeld:       pausedCarryHeld,
			YieldPaid:             yieldPaid,
			YieldQualified:        countYieldQualified(tree, rootID),
			LockedCapital:         lockedCapital,
			PointsBonusPaid:       pointsBonusPaid,
			PointsHeld:            sumPointsAccrued(tree, rootID),
			RankBonusPaid:         rankBonusPaid,
			RanksAchieved:         countRanksAchieved(tree, rootID),
			ReferralPaid:          referralPaid,
			RoyaltyPaid:           royaltyPaid,
		}
		results = append(results, res)

		if w != nil {
			fmt.Fprintf(w,
				"period=%d  inflows=%s  events=%d  theta=%s  paid=%s  margin=%s  pkg_caps=%d  daily_caps=%d  solvent=%v  size=%d\n",
				p, inflows.StringFixed(2), len(events), theta.StringFixed(4),
				totalPaid.StringFixed(2), margin.StringFixed(2),
				br.PackageCapHits, br.DailyCapHits, solvent, tree.Size(),
			)
		}
	}

	if w != nil {
		fmt.Fprintf(w, "\nCUMULATIVE MARGIN over %d periods: $%s\n",
			s.Periods, cumulativeMargin.StringFixed(2))
	}

	return results, nil
}

// consumePVAfterPayments deducts the points equivalent of paid blocks from
// each ancestor's legs and carries the surplus on the strong side.
func consumePVAfterPayments(tree *Tree, paid []Candidate, plan PlanConfig, theta decimal.Decimal) {
	blockPoints := decimal.NewFromInt(int64(plan.BlockSize))
	// Aggregate blocks paid per ancestor.
	blocksByAnc := map[int64]int64{}
	for _, c := range paid {
		// Effective blocks after θ — round down so we never claim more than paid.
		effBlocks := decimal.NewFromInt(int64(c.NewBlocks)).Mul(theta).Floor().IntPart()
		blocksByAnc[c.AncestorID] += effBlocks
	}
	for ancID, blocks := range blocksByAnc {
		if blocks <= 0 {
			continue
		}
		anc := tree.Get(ancID)
		if anc == nil {
			continue
		}
		consumed := blockPoints.Mul(decimal.NewFromInt(blocks))
		lTotal := anc.LeftPV.Add(anc.LeftCarry)
		rTotal := anc.RightPV.Add(anc.RightCarry)
		anc.LeftPV = decimal.Zero
		anc.RightPV = decimal.Zero
		// Burn consumed from BOTH legs (matching mechanic).
		lRemain := lTotal.Sub(consumed)
		rRemain := rTotal.Sub(consumed)
		if lRemain.Sign() < 0 {
			lRemain = decimal.Zero
		}
		if rRemain.Sign() < 0 {
			rRemain = decimal.Zero
		}
		anc.LeftCarry = lRemain
		anc.RightCarry = rRemain
	}
}

func decayCarry(tree *Tree, _ int64) decimal.Decimal {
	expired := decimal.Zero
	for _, n := range tree.nodes {
		expired = expired.Add(n.LeftCarry).Add(n.RightCarry)
		n.LeftCarry = decimal.Zero
		n.RightCarry = decimal.Zero
	}
	return expired
}

func allNodes(tree *Tree, rootID int64) []*Node {
	out := make([]*Node, 0, len(tree.nodes))
	for id, n := range tree.nodes {
		if id == rootID {
			continue
		}
		out = append(out, n)
	}
	// Sort by ID to keep iteration deterministic. Without this, Go's randomised
	// map iteration yields different period results from the same seed.
	sortNodesByID(out)
	return out
}

// markFounder marca al nodo recién colocado como fundador con probabilidad
// FounderFraction (ADR-0018: en el lanzamiento v2.0 = 1.0, todos fundadores).
// Consume un tiro del RNG sólo si la fracción es > 0, para no alterar las
// secuencias de escenarios existentes con fundadores apagados.
func markFounder(tree *Tree, id int64, plan PlanConfig, rng *rand.Rand) {
	if plan.FounderFraction <= 0 {
		return
	}
	n := tree.Get(id)
	if n == nil {
		return
	}
	if plan.FounderFraction >= 1 || rng.Float64() < plan.FounderFraction {
		n.IsFounder = true
	}
}

func sortNodesByID(s []*Node) {
	// Insertion sort is fine for sim sizes; avoids importing sort.
	for i := 1; i < len(s); i++ {
		j := i
		for j > 0 && s[j].ID < s[j-1].ID {
			s[j], s[j-1] = s[j-1], s[j]
			j--
		}
	}
}
